### PR TITLE
suggestion to create license.md for an overview of all repository licenses including license type, year, and licensors

### PR DESCRIPTION
**Pull request by Mitzi-Laszlo**

### CODE REVIEW

**Comment by Mitzi-Laszlo** [comment]
Yes, agreed, would be good to define the parameter of Solid software here. In the Community Repo Readme "solid software" links to https://github.com/solid. Is this a sensible parameter? 

(This brings up another parallel theme -  are [Solid apps](https://github.com/solid/solid-apps) part of Solid? Would it make more sense to have the owners of the app publish the app? (is this another pull request?))

**Comment by Mitzi-Laszlo** [comment]
Change is sound, thanks for making that suggestion. Co-licensing all repositories with MIT and CC license may simplify and also cover both text and code.

**Comment by Mitzi-Laszlo** [comment]
@RubenVerborgh Do you think the new sentence proposal is clearer? Any other suggestions on how to advance?

**Comment by RubenVerborgh** [comment]
I think it's still problematic; https://github.com/solid does not point to code, it points to a collection of repositories. The repositories in that collection have different licenses; none of them are co-licensed.

**Comment by Mitzi-Laszlo** [comment]
Indeed, the changes to the overview still need to be reflected in the individual repos under the https://github.com/solid

**Comment by Mitzi-Laszlo** [comment]
https://github.com/solid/community/pull/43

**Pull request closed without merging**
