### PR TITLE
Addition: respecting people's time and effort by listening actively

### PR DESCRIPTION
**Pull request by RubenVerborgh**
Possible implementation of #5.

### CODE REVIEW

**Comment by melvincarvalho** [comment]
> reply to relevant statements and questions they write

This seems rather onerous.  Lots of reasons not to require this, but one obvious one.  You could just bloat the issue with questions, and practically kill a conversation.  Someone asking a question is not owed an answer.  An answer is based on an individual's knowledge, their time and a judgement on whether it will advance the conversation.  Questions can also be leading, off-topic or taking the conversation into a direction where things like a strawman attack can be applied.  This does happen in solid.

It strikes me that this is an attempt to change the code of conduct in order further a certain style.

I also find this somewhat inconsistent.  On two occasions I have had my github comments deleted by @RubenVerborgh which were valid requests, and relating the deletion of repositories.  There was no good reason to delete those items.  To my knowledge no one else has done that in solid ever.  I have never had that done to me on github either.  I would prefer the code of conduct to be say something about questions being allowed to be stated for historical record without being deleted.  IMHO answering a question is always a judgement call, based on the context.

**Comment by RubenVerborgh** [comment]
> You could just bloat the issue with questions

That would be trolling; that should be covered in the rest of the terms.

Note that the suggested text says "relevant".

> and practically kill a conversation.

Note that a conversation can also be killed by not replying to any question; but that is not covered under trolling. Hence this suggestion.

> Someone asking a question is not owed an answer.

No, but if that question was relevant and necessary to understand the concern raised, then there should also be no expectation by the original poster of being understood or listened to, yet that seemed to be the case in those issues that prompted the present pull request.

And I don't like the idea of ignoring people; everyone's concerns should be heard—but then they should also be willing to clarify their concerns appropriately.

> Questions can also be leading, off-topic or taking the conversation into a direction where things like a strawman attack can be applied.

These are all covered under "relevant" to me.

Also, a poster can also simply argue that the questions were leading/off-topic/etc. Not replying at all is not being mindful of people's time.

> It strikes me that this is an attempt to change the code of conduct in order further a certain style.

Absolutely. A style that enables efficient communication. There have been multiple instances of threads were a poster expects to be listened to and reckoned with, even though they outright refuse to clarify their point. That is wasteful.

> I also find this somewhat inconsistent. On two occasions I have had my github comments deleted by @RubenVerborgh which were valid requests, and relating the deletion of repositories.

Perhaps we should add "tu quoque" AKA "appeal to hypocrisy" to the list above, after the strawman attack 😉

But that's a different topic, feel free to start another thread.
I will reply below shortly.

Those comments were deleted because I perceived them as an attack on my professional integrity. The comments were describing actions I had taken on behalf of Inrupt, in such a manner that it made me look unprofessional. These comments were repeated comments that were made despite an explicit question beforehand to resolve the matter offline. Hence my decision to remove.

> I would prefer the code of conduct to be say something about questions being allowed to be stated for historical record without being deleted.

Please raise a new issue.

> IMHO answering a question is always a judgement call, based on the context.

Definitely. And this change is proposed to inspire such judgement: if people pose relevant questions that are necessary to understand someone's point, these questions should at least be considered for an answer.

So let's be completely transparent. Yes, the direct cause that prompted me to create #5 is indeed your continued refusal to back up certain outrageous claims with technical arguments in a couple of recent threads. However, don't see this proposal as directed against you; I purposely worded it in a way that is broader and applies generally.

Could you please let us know whether you (dis)agree with the general idea ("be mindful of people's time")? If so, is your issue with the specific phrasing of the text that follows it? If not, why shouldn't contributors be mindful of other's time?

(^ This being an example of a relevant, focused question, which, when ignored in a subsequent reply, does not advance the issue.)

**Comment by RubenVerborgh** [comment]
@melvincarvalho Thinking about

> Someone asking a question is not owed an answer.

some more, I see that this could indeed be tricky.

So I will experiment with another approach, where raised concerns are given an issue of their own. These issues then serve as a place to post reproducible cases in which the concern or bug manifests itself. I have tried this with one (randomly selected) of your concerns: https://github.com/solid/node-solid-server/issues/975 (I purposely did not do this for your other concerns in order not to spam you, but feel free to create and self-assign such issues for everything you see as important.)

If this approach is successful, then perhaps we have a better answer to #5 than the current PR #6.

In any case, I hope this brings us progress.

**Comment by RubenVerborgh** [comment]
Update: raising https://github.com/solid/node-solid-server/issues/975 has indeed established in record time that there are no technical arguments for "LDP server compatibility broken". So doing this might be a viable way indeed. Will try this on future points made without technical arguments to see if it helps.

**Comment by melvincarvalho** [comment]
> Could you please let us know whether you (dis)agree with the general idea ("be mindful of people's time")?

It's hard to know what to make of this.  In the context of a code of conduct.  I mean it's quite vague, a bit like saying time is valuable.  Well, we are all constrained by time, both individually, and as a project.  How can it be enforced etc.?  Something like being respectful, or being constructive, I think can be more easily enforced because often the cases will be clear cut.  I think between these two it covers being mindful of people's time both your own and others.  No one is owed your time, but objections should be normally be heard -- which is what we do in working groups.

I much prefer something like an IETF type guidance here : 

https://tools.ietf.org/html/rfc7282

Which says asks an objector, "can you live with a certain outcome".  If so, we move on.  We try not to vote, because vote stuffing is too easy.

> to back up certain outrageous claims

Comments such as this are unhelpful.  What could be done better, aside from removing the hyperbole, is to state the exact comment that you object to, or the argument.  

> established in record time that there are no technical arguments for "LDP server compatibility broken"

This is a better way of phrasing things, so that there is a reference to the statement you are arguing against.  I'm someone surprised in this case, as I stated my argument (in note form, rather than as an objection, and one I could live with).  I stated to you on a very large number of occurrences publicly and out of band this case.  I didnt back down once, yet you went away thinking there were no technical arguments.  

Of course there are.  NSS introduces a bespoke rewrite rule, that is hard coded into it, that no other web server (LDP or otherwise), on the planet will have.  So swapping out one web server for another will cause breakage.  My request to make it configurable as was turned down, so I just left it in as a note.  For which I was personally and unfairly attacked for.  Indeed, I asked the inrupt community manager to help out but they told me they were too busy.  That's really the problem here.

So no, I'm not buying your alterations to the code of conduct.  If you can find another well received code of conduct with a similar type of language that would lend more weight to the text.

**Comment by RubenVerborgh** [comment]
> Something like being respectful, or being constructive, I think can be more easily enforced because often the cases will be clear cut.

Myeah, there are many definitions of "respectful" too. I didn't find it a sign of respect that explicit questions, intended to help someone state their case, were repeatedly and insistently ignored.

Unfortunately #5 and #6 seem to have turned into another discussion about https://github.com/solid/node-solid-server/issues/975 and others, so there's no point in continuing. If you cannot see that I'm actually one of the few people left (if not the only one) who are willing to take your concerns seriously, and that you're not helping your own case by not answering sincere questions, so be it. I will leave it to you to find support for your cases in the future.

-----

Regardless of the above, I still think this PR presents a viable contribution. We don't have any item yet on listening to others, and I think that is a good thing to have.

**Comment by melvincarvalho** [comment]
> If you cannot see that I'm actually one of the few people left (if not the only one) who are willing to take your concerns seriously, and that you're not helping your own case

How very unpleasant.  What cause is that exactly?  The cause that I have spent the last 10 years volunteering for this project without pay and without complaint.  Sacrificing, time, pay, health, family, relationships just to make the web a bit better, because others would not.  And how nice do you think it is to have you come in and question my character?

> Those comments were deleted because I perceived them as an attack on my professional integrity.

This is 1. a fabrication and 2. unjustified even were it not.

What actually happened was that you deleted a repository that was in use without archiving it and without backing it up.  That was your own attack on your professional integrity.  I simply asked you to hold off until we could talk about it.  You deleted those comments (twice!), which covered your tracks.

Second incident was when exactly the same thing happened and I questioned where the repo went.  You then straight out denied it.  However the audit log implicated you.  

And how about the time you deleted private keys off a server, and I fortunately had a back up.  Did I ever do anything other than help you?

And what about when you changed the headers and warp and pretty much all my apps broke.  You never fixed any of that.  I was left to.

On none of these occasions did I attack your professional integrity, in fact, I took a long time out to help things recover, and rebuild trust.  I didnt question you, only helped you.  Deny that if you will.

I only objected strenuously when you deleted my github comments.  How professional do you think it is to do that to a member of the project that has been there longer than you?  I said it was unacceptable, which might have been slightly strong language, but the sentiment was sound.

Even still I worked with you to resolve things privately, until you decided to attack me publicly.  What am I supposed to do.  Sit there and be your punching bag?  I've worked longer and harder on this project than you ever will, and have only ever expected the minimum respect that you would show a colleague, or even a volunteer.

You are a talented developer, I have always told you that.  And I still believe it.  But attacking a volunteer reflects poorly on you, on the project, and on inrupt.

**Comment by melvincarvalho** [comment]
> here's no point in continuing

If you say so, then OK

>  If you cannot see that I'm actually one of the few people left (if not the only one) who are willing to take your concerns seriously

How would I see that, eh?  

This is a barb, a jibe, and frankly, a horror.

Thank you so kindly, dear sir, that you are that last of the last that, will even endugle me with all my faults.  So nice, so good.

>  If you cannot see that I'm actually one of the few people left (if not the only one) who are willing to take your concerns seriously

Brilliant.  Frankly, I would advise you to have a lil read on your short passive aggressive gibes on this thread.  And, well, examine your echo chamber.  

Do like you, sir.  But this commentary is, im afraid, abject.

**Comment by melvincarvalho** [comment]
@RubenVerborgh let me take this opportunity to apologize for my tone on this issue and others.  It was not professional of me.  No excuse, but I have had some stress personally, lately.  I do appreciate the feedback and technical points that you make, and I will try to listen better, in future.

**Comment by RubenVerborgh** [comment]
@melvincarvalho Apologies if you felt attacked by any of my statements, that was not my intention. My disagreements are purely technical. We (as a community) need to find ways to listen to each other more efficiently. We all have the best of intentions, communication is just inherently hard.

**Comment by RubenVerborgh** [comment]
@Mitzi-Laszlo There's no conclusion yet? It's an open PR.

**Comment by Mitzi-Laszlo** [comment]
@RubenVerborgh fair point. 

@melvincarvalho what would you propose as a solution to be able to bring this pr to a conclusion and move forward?

**Pull request merged**
