### PR TITLE
assorted typo and markup fixes

### PR DESCRIPTION
**Pull request by TallTed**

### CODE REVIEW

**Comment by TallTed** [comment]
@Mitzi-Laszlo -- This should take only a few minutes to review and merge...

**Comment by Mitzi-Laszlo** [comment]
@TallTed thanks for taking the time to review this, looks good to me. Once the 14 days have passed to give people the chance to review and comment as agreed on by the [process](https://github.com/solid/community) I'll make sure it gets reviewed immediately. Of course this is a small change so 2 weeks does sound long, just wondering how to define small changes from big ones and who decides on which time window to pick when. Almost easier to just stick to 14 days for everything. Open to suggestions on how to improve.

**Comment by TallTed** [comment]
A two-week review period seems rather absurd for obvious typo fixes and document layout improvements such as these.  I think that review period was/is meant for *material* changes -- substantial code changes, revision of spec text, UI redesign, etc.

**Comment by Mitzi-Laszlo** [comment]
https://github.com/solid/community/pull/53

**Pull request merged**
