### PR TITLE
Create solid-events.md

### PR DESCRIPTION
**Pull request by Mitzi-Laszlo**

### CODE REVIEW

**Comment by RubenVerborgh** [comment]
Also DWeb Summit 2 August 2018: https://solid.github.io/dweb-summit-2018/

**Comment by Mitzi-Laszlo** [comment]
Maybe we should distinguish between Solid Events (meetups specifically about Solid for Solid community) and places where Solid was mentioned which could also include articles.

**Comment by Mitzi-Laszlo** [comment]
Option 1: make headings in solid-events.md such as "Solid Events" "Solid Press" 

Option 2: make another md file in the community repo called solid-press.md (or something) that is specifically for public speaking and article links. 

Preferences?

**Comment by kjetilk** [comment]
Dunno, but I think the other header should possibly be "Solid participation" or something like that.

**Comment by Mitzi-Laszlo** [comment]
how about? https://github.com/solid/community/pull/19

**Pull request merged**
