### PR TITLE
Fix invalid links

### PR DESCRIPTION
**Pull request by cldwalker**
Hi!
Thanks for the helpful documentation as I've been able to quickly get a pulse on the community. Solid looks exciting. I noticed a couple links were invalid so I ran [this tool](https://www.npmjs.com/package/markdown-link-validator) and got the following output:

```
Found a total of 178 links in directory "/Users/me/code/repo/community":
    156 valid
    22 invalid
```

I have fixed all of the invalid links except for the repository manager link which is fixed in #44. I could fix that in this PR if you'd like. 

To prevent future invalid links, I'd recommend setting this up to run on every commit via a CI tool like travis. I'd be happy to set that up if desired. I'm guessing from the community roles that kjetilk would be the one to ask about CI access

Cheers, Gabriel

### CODE REVIEW

**Comment by megoth** [comment]
LGTM ^_^

**Comment by Mitzi-Laszlo** [comment]
Thank you @cldwalker and your suggestion sounds good to me. Indeed, @kjetilk would be the right person to reach out to to set that up. 

Considering this is a pull request about updating broken links it can be reviewed in three days.

**Comment by cldwalker** [comment]
@kjetilk Per above I've recommended setting up a CI process to prevent future linkage breakage using a one-line node command. The command detects internal and external links are valid. Mitzi is onboard with the suggestion. If you're onboard with this, what CI service does the Solid team use so I can submit a PR for it? It seems like [travis](https://github.com/solid/node-solid-server/blob/master/.travis.yml)

**Comment by kjetilk** [comment]
Yeah, that sounds like a great idea, @cldwalker ! We use travis, yes, so a PR for this would be very welcome!

**Pull request merged**
