### PR TITLE
Rule of Thumb rather than Code of Conduct

### PR DESCRIPTION
**Pull request by Mitzi-Laszlo**
People of Solid, 

I have a radical proposal to get rid of the code of conduct completely and replace it with a single rule of thumb ‘Keep to the content.’ 

Why? (you may ask) 

The code of content is stating points that are so obvious that they should not really need to be said. Plus, if we get to a stage where we feel they need to be said, then we have more fundamental social dynamics that need to be adapted to build a more trusting environment. 

Secondly, if we have rules, somebody has to enforce them, which would (according to the current description of roles) be me as Solid community manager. Realistically speaking, if a person isn’t professional that reflects, more than anything, on their own credibility. 

Blocking people is an unrealistic solution because they can create another profile, so that’s a pretty futile approach.   

What I can do, as community manager, is work hard to contain off-content conversations so that on-topic conversations are more centre stage.

Thoughts?

Mitzi

### CODE REVIEW

**Comment by MattDorrian** [comment]
People should use their 'Moral Compass' at all times. We cant have you getting involved in anything trivial surely that would be considered a waste of natural resource. 'Imho' I'd ban this term as it can often be construed as condescending. We are all Humble and we move together as a unit.

**Comment by konobi** [comment]
To be honest, a lack of a CoC would likely be cause for me to drop participation.

While there are challenges to enforcement, the benefits to the project in terms of more open participation, from a wider diverse set of individuals shouldn't be dismissed. If enforcement is _the_ challenge around this currently, I think it would be prudent to provide some focus on that to ensure that the entire community takes a role on this rather than lumping responsibility onto a single individual or small group.

**Comment by megoth** [comment]
I agree that as the code of conduct stands today, ie a document very hard to enforce, it has little value. But I think this is an important document to have wrt events and other physical manifestations of community efforts, where banning socially unacceptable behavior might be easier. I also think the document is a good outline for a social contract we want to uphold for the community in general, even though it's hard to enforce online.

Lastly I think it sends a very negative signal to get rid of the CoC as it would probably be spearheaded by various groups (that we probably don't want to be associated with) to misconstrue it as "Tim Berners-Lee, the father of the web, don't see the point of having code of conducts". I think it might hurt the work that has been done on code of conducts in general, which would be very sad, as I know that CoCs have been useful in other communities.

If this is something a lot of people support (to get rid of the CoC), it should at least be finalized with a decision made by the community leader.

**Comment by megoth** [comment]
I would also argue that the very fact that it is a document hard to enforce might be the thing we should do something about - what acceptable mechanisms can we make use of/implement in order to make the CoC more enforceable?

**Comment by MattDorrian** [comment]
A code of conduct is there for a reason and removing it for this would be considered pandering to a minority. Maybe replace the word 'enforce' with 'ignore' to a point where productivity is being impaired, then members with granted permissions can just lean in switch them off, explain why and if they promise to be good little inrupters switched back on again.

**Comment by MattDorrian** [comment]
What about a Mute button! If enough people push it generates a 2 hour cooling off period. Anonymously.  pick a number....10?

**Comment by MattDorrian** [comment]
Can probably nail that down a bit.   Admin levels cant be muted for obvious reasons.  More than 3 mutes in a month would generate an overview of the members recent transcripts for the assigned 'Pest controllers' so they can decide if any coarse of action is required. In terms of 'mechanisms' if I was 'Muted' I would first consider why, and secondly learn from it. 
Fully automated to the point where action is required and presented with all the information to make an informed decision.

**Comment by jeff-zucker** [comment]
I think the community definitely needs a code of conduct especially in regards to safe-workplace issues, diversity, and equity.  That said, there are many issues of common politeness which impact the community but are probably better handled informally by mediation and conversation.  I'd support a dual approach - a formal code of conduct with a grievance procedure and an informal "let's see if we can work this out" approach  with perhaps a group of mutually respected advisers as facilitators.  The recent squabble at 
 https://github.com/solid/community/issues/59 should not, in my mind, be handled as a code of conduct issue - it relates to something that took place on an individual's web space, not a space that enforcement is either possible or desirable except in the case of harassment.  But we as a community could offer a space (perhaps a private chat with mutually agreed on participants) in which we could encourage people to work out their differences or advise a grievance if appropriate.  A public github discussion etched in institutional memory is useful for establishing norms of conduct but some things are better de-escalated in private without permanent record.

**Comment by mediaprophet** [comment]
there are Relevant United Nations Agreements which could be made available as RDFS / OWL - ontologically referenceable concepts. 
http://www.un.org/en/documents/udhr/ 
https://www.un.org/womenwatch/daw/cedaw/text/econvention.htm 
https://www.ohchr.org/en/professionalinterest/pages/crc.aspx 
https://www.ohchr.org/en/professionalinterest/pages/opsccrc.aspx 
https://www.ohchr.org/en/professionalinterest/pages/opaccrc.aspx 
https://www.ohchr.org/en/professionalinterest/pages/cescr.aspx 
https://www.un.org/development/desa/disabilities/convention-on-the-rights-of-persons-with-disabilities.html 
https://www.ohchr.org/en/professionalinterest/pages/cat.aspx 
https://www.ohchr.org/en/professionalinterest/pages/cerd.aspx 
https://www.ohchr.org/en/professionalinterest/pages/opccpr1.aspx 

which in-turn form an internationally agreed set of principles. 

thereafter; a dispute resolution process,

noting;
- https://en.wikipedia.org/wiki/Wikipedia:Dispute_resolution 
- https://en.wikipedia.org/wiki/Dispute_resolution 

And Incident report structures - ie: https://en.wikipedia.org/wiki/Incident_report 

that is processed by a community nominated 'dispute resolution practitioner' who is subject to 'conflict of interest' protocols that mean they have to bow out if a conflict exists, is the type of process that should be done.

facilitating an argument in public domain, with false-statements incorporating a means in which to seek continued engagement by a disaffect actor who has no available remedy - 'ain't cricket'.

imho.

i'm working on the ontologies.

**Comment by mediaprophet** [comment]
I also note - my view of 'core solid apparatus' is that it's a bit like a linux kernel, in that, it's kinda impossible to isolate its use from considerations around 'human rights'. 

that said - there is a distinction between the 'core solid apparatus' and various implementations, of which, inrupt is leading the charge - in whatever way it seeks to do.  

Yet - underlying whatever it is that inrupt forms a lens as to exact their view, on the best possible future for us all, the design of w3c standards and thereafter also - solid - means, its important to be inclusive.  Even with people you don't want to work with or be involved with in any other way. 

so - the challenge becomes - how to form triage means - that is not build upon 'inrupt owns this environment' but rather - social-informatics that relate in-turn to the underlying 'open source' (or 'pro-human') works that in-turn cause informatively defined 'ripple effects' incorporating both private and public data; built upon moral virtues & overall, something akin to 'personhood'.  that save exceptional circumstances, or as noted re: conversations with Noam Chomsky in an effort to 'web science' the ontological debate issues; he noted,

"The fact that there are pressures and costs does not absolve people of their moral responsibility. The primary custodian of one’s actions is oneself."  (noam's words)

to which i responded that i agreed - save exceptional circumstances (such as human trafficking) where the person is unable to be the beneficial owner, of their capacity to make choices.

no-matter how that is brought about.

The idea of not supporting a persons capacity to work on 'solid' - no matter whether or not you want to work with them at all - seems morally reprehensible - akin to suggesting, that because you don't like them, they shouldn't be allowed to use money - or moreover - [knowledge capital](https://www.oecd.org/sti/inno/newsourcesofgrowthknowledge-basedcapital.htm)

yet, it is also the case that i believe - if a person outright breaches [article 30 of the UDHR](https://www.un.org/en/universal-declaration-human-rights/index.html) - considerations must be made.  If an legal actor stands for nothing, it is truely worthless...

conversely, [social informatics](https://www.webizen.net.au/about/references/social-informatics-design-concept-and-principles/) have real-world implications.  So, decisions & distinctions need to be made, in this 'bleeding edge' area of global knowledge economy innovation.

again - imho.

timo.

**Comment by Mitzi-Laszlo** [comment]
Just to quickly clarify, my suggestion to simplify the code of conduct certainly isn't a suggestion to not be civil. 

Would you agree that right now the code of conduct is so detailed yet incomplete that it becomes a game of finding the loop hole in between the rules and seems mainly to be mentioned by people who are clearly not being civil themselves rather than encouraging civility?

@jeff-zucker Agreed that there should be a way to report grievances, for example by reaching out to the Solid team with an issue or in private and then having a clear predefined process to handle the grievance. 

Beyond the 'let's see if we can work this out' through talking approach, how could we realistically enforce civility in a voluntary public forum?

Muting/ blocking individuals is ineffective because they can simply create another profile and also is the opposite of trying to work it out together. Muting/ blocking runs the risk of aggravating the irritation rather than encouraging individuals taking responsibility for our own actions and words.

**Comment by mediaprophet** [comment]
any pointers about how to improve the notation https://github.com/WebCivics/community/blob/master/ontologies/UDHR.ttl ??

**Comment by JollyOrc** [comment]
I disagree with the "so detailed yet incomplete" part. And I completely support the actual content of the CoC, there is nothing wrong in there.

Instead I think the issue is that it is a bit muddled. DOs and DON'Ts are mixed, there are common place statements ("disagreements happen") and overly complex encouragements. 

Example:

> Stay on topic. Remember others voices need to be heard as well as yours and you must allow the space for other members to participate (e.g. don't monologue or respond to every comment).

This actually contains three separate things:
- stay on topic for the conversation
- keep your contributions to a discussion short
- allow others to be heard

All three are excellent advice, although one could argue that ignoring it would contribute to a non-fruitful conversation (or worse: Make you a bore!) but isn't actually a code of conduct violation in the sense that someone got hurt by it.

So it might be useful to re-word the Code a bit to be more streamlined. I personally like how they do it with the Contributor Covenant: https://www.contributor-covenant.org/version/1/4/code-of-conduct

Note also in this, a problem isn't raised via a public github incident but instead via an Email address. That way a grievance doesn't immediately gets put onto a public record where the pressure for everyone involved to defend their status is so much higher.

**Comment by mediaprophet** [comment]
> Muting/ blocking individuals is ineffective because they can simply create
> another profile and also is the opposite of trying to work it out together.
> Muting/ blocking runs the risk of aggravating the irritation rather than
> encouraging individuals taking responsibility for our own actions and words.
>
> Blocking relates to the legal entity involved, rather than more simply the
identifier.

From a point of view of semantics, whilst change of URIs is an important
use-case (ie: departments of foreign affairs approved purposes, those in
witness protection related programs - alongside people changing their names
when they're getting married - which mostly affects women) - i think it is
reasonably noted, that this is actually very difficult to achieve.

An example can be illustrated by simply creating a new social media
account, for instance facebook - it'll make suggestions that you become
friends, with all the 'friends' on your old account - which is an overly
simplified example of a far broader reality check when it comes to
dissociative decision trees as a response to identity related issues.

**Comment by mediaprophet** [comment]
The other very quick solution, might be to employ the W3C community rules which are well understood and well developed - which (at least for the meantime) would create a well-thought out stopgap. 
(if nothing more)

**Comment by mikeadams1** [comment]
A Grievance Resolution Committee should be by the Solid Community, and should include an avenue for a person to seek a ruling on an issue that is not necessarily stipulated in the Code of Conduct, among other things. The Solid Community could appoint a member of Inrupt Inc. to be a non-voting mediator of the Solid Grievance Resolution Committee ("GRC"). Actually, all solid pod providers with X amount of users should have to create there own GRC.

**Comment by mikeadams1** [comment]
If a grievance is filed on a member, the members should have to show that they have previously tried to settle the matter. They should be given an opportunity to withdraw the grievance in the event a settlement is reached between the parties to the grievance. The object should be to come to a settlement, even Courts prefer settlements.

**Comment by mediaprophet** [comment]
A problem with tying inrupt to the process includes considerations of TimBL
being a politically exposed person - or similar to that form of
definition.  Therein, bad actors may seek to cause harm via community
engagement with the broader community - that is beyond the organisational
governance structure of inrupt inc. specifically.

Consideration for the structural framework built into W3C should be
considered

Therein - the methodology becomes 'loosely coupled'.  Equally, the online
estates not managed by Inrupt specifically - those that are distinct to the
online engagement modals that are managed by inrupt specifically - may well
be better equipped if bound to a dual-strategy that employs one set of
rules for those otherwise bound to W3C CG rules (and arbitration protocols)
- and another for those that are not.

yet moreover - this type of issue is not simply isolated to this community
group but rather a broader problem, that IMHO may be well-served with an
ontological response, that i'm working  on myself regardless.

I also found https://github.com/trustgraph which looks like it may be
easily integrated with solid.  therein - whilst some may relate to rules
that have w3 jurisdictional frameworks, perhaps pod providers (inc. inrupt)
could extend this to support others.

IMHO.

**Comment by mikeadams1** [comment]
Each solid pod provider is responsible for their own Solid Community. I believe this has already been established, and as such, Inrupt Inc., should be deciding matters that are related to their own solid pod community.

IMHO, we should create the documentation and implementation as the first generation of sold pod providers, and all future solid pod providers can use it as a guideline for creating and adopting their own community rules. I do not believe though that, any one solid pod provider should be policing another solid pod providers community.

**Comment by JollyOrc** [comment]
Just for understanding: What is the intended scope here? The community that develops and builds Solid as a technology, the community of pod ownsers, or the whole lot of people that will eventually use Solid in an interoperating linked world?

**Comment by MattDorrian** [comment]
All good stuff. Yet I am seeing the polar opposite of the concerns at the minute everyone I have encounted and witnessed have impressed including the 59ers! As passionate individuals opinions clash things will invariably get heated at times. As Timothy rightly suggests the W3C would provide a natural back stop and as the project evolves multiple mediation chat rooms would appear. This is why a function should exist that initiates the mediation processes which ever form that takes. Taking unresolved issues out of the lime light getting them resolved maybe as a community and so the process continues.

**Comment by mediaprophet** [comment]
the 'gitter/solid' community serves all 'solid pod providers' currently.

Alliance agreements, extending the contract for the web - can offer a means
for a group to collaboratively support an ideological approach.  Due to
international complexities with respect to juristional differences and
enforceability / forming binding 'moral rights' - human rights, generally
have some form of support in some way, internationally.

IMHO.

**Comment by mikeadams1** [comment]
The community that develops and builds Solid should have their own GRC, COC, and the like, and as for pod providers, they should have to incur the responsibility and expenses of creating and maintaining their own GRC, COC, TOU that would inure to the benefit of their solid pod community users.

**Comment by mediaprophet** [comment]
re "scope" afaik - there have been similar challenges in an array of other
decentralised / commons & 'open' 'headless' communities.

CreativeCommons has an RDF ontology, which is part of how it works.  I'm
looking to define far more extensible solutions, where the case is - for
whatever reason, others have not.

Still v.interested to know if i'm the first person whose started putting
human rights into an RDF / Machine Readable ontology.  IMHO - that's a big
deal.

first piece being drafted -
https://webcivics.github.io/community/ontologies/UDHR_update.ttl

**Comment by mediaprophet** [comment]
noting - the entire 'solutions framework' could be implemented as a solid
app, and would, imho, be a great contribution and perhaps opportunity - for
others to start using solid servers to deal with incident reports /
disputes - using private/public semantics, inferencing capabilities, etc.

**Comment by mikeadams1** [comment]
At some point, the baby will outgrow the incubator, and each Solid Pod Community will have to stand on their own merits. Although each solid pod community will make up the Solid Pod Ecosystem, each Solid Pod Provider should have to have in place their own policies and procedures. This is primarily why I believe @Mitzi-Laszlo stated she was not able to make a judgement in #59.

**Comment by MattDorrian** [comment]
A solutions framework that can be embedded

**Comment by mikeadams1** [comment]
The pod provider that has set up NSS on Solid.authing.cn by default makes all of the root home pages private, does that mean that Inrupt Inc., can force them to make them public by default? The answer is no, they cannot and that means if I have a grievance about that matter or issue, I must take it up with the owner of that solid pod community. That is why I suggested in #59 that we establish a Grievance Resolution Committee.

**Comment by mediaprophet** [comment]
FWIW

FYI - re 'growth' - it was once called RWW.  IE:
http://dig.csail.mit.edu/2014/Papers/presbrey/thesis.pdf

it's grown alot since.

whilst my implementation methodology is about knowledge banking
https://www.webizen.net.au first started in 2000, but significantly
uplifted from 2010 due to the apparent demand for informatics solutions
that provide improved means to protect vulnerable people by applying
pervasive surveillance capabilities - towards the 'intended beneficiaries',
whom still deserve to have those capacities made available as to protect
their human rights in a court of law:
https://www.webizen.net.au/wp-content/uploads/2018/09/Credential-enabled-Identity-5.svg


therein - terms need precedent - and need to be in RDF.

also applies for any other methodological implementation strategy other
than 'knowledge banking providers', afaik.

**Comment by MattDorrian** [comment]
Mike Mitzi couldn't make a judgement because the 'crime' (I use that term very lightly) was not commited under her jurisdiction and in her domain. So trying to create an 'optional' tool that can aid future Solid pod holders combatting these types of issues can only help expediate the processes in order to visualise their individual goals.

**Comment by mikeadams1** [comment]
Agreed, Mitzi works for Inrupt inc. and the domain of inrupt.net. If the offense occurred on another pod providers community, she still would have had no authority to enforce Inrupts policy. That being said, I do believe that #59 was outside of the scope of her authority to create.

**Comment by mediaprophet** [comment]
I'd use the term 'allegation', which seemingly has no method for ensuring
someone is 'cleared of wrongdoing' or otherwise atm...

which should be fixed.  Interference patterns are produced no-matter
whether a choice is made or is not - as no choice, is still a choice.
https://www.youtube.com/watch?v=Jqm4f55soJQ

**Comment by mediaprophet** [comment]
Note also - it is impossible to delete another persons comments in google
docs:
https://www.quora.com/Can-I-delete-other-peoples-comments-on-Google-Docs

so, the ontological framework needs to have some notation frameworks around
misinformation & similar.

**Comment by mikeadams1** [comment]
You mean Unsupported Conclusory Allegation!

**Comment by mediaprophet** [comment]
mike adams - comment thread is Re: [solid/community] Rule of Thumb rather
than Code of Conduct (#66)

If you want to go on a personal mission - i believe the process is
currently to create a ticket and to say whatever you want publically,
without repercussion.  If you feel compelled to do so, i'd recommend
logging another ticket to get on the bandwagon - just make sure the subject
/ scope - is defined in a way that gets to what it is you're actually
trying to achieve. - not many consequential issues, other than 'staying on
topic'.

**Comment by mikeadams1** [comment]
Sorry, I digress.

**Comment by mediaprophet** [comment]
Also - The suggested commit https://github.com/solid/community/pull/66/commits/2c0b6f1571e6776282e633f5c47b82ce262c692a 

is a very poor suggested commit, imho.  as noted above (before reading the commit) i think there is an opportunity to do far better to protect the safety of those willing to put their time into solid freely, at their expense - than may otherwise be incurred - as an expense if no safety related policies were considered in relation to the management of this very important community.

as noted - w3c CG documents include,
- https://www.w3.org/community/about/agreements/cla/
- https://www.w3.org/Consortium/cepc/ 
- https://www.w3.org/Consortium/pwe/ 

It may well be the case that estates not governed under the 'solid by inrupt' framework, may be able to be surrogated for governance purposes via W3C, or perhaps WebFoundation, or perhaps WebScience,

but the simple thing - would be to simply point at the https://www.w3.org/community/solid/ group, and encourage people to be involved with it.

W3C is about standards, not software implementations.  To be successful, solid will need to have interoperable standards that makes it work 'in every browser', using all sorts of different implementations, on the 'server side' (even if, its built into a browser)

**Comment by MattDorrian** [comment]
Maybe a place to start is to categorise the Mediation 'Rooms' Where defined Inrupt members can control, monitor, advise and maintain the flow of the projects.
Directional Vision  
Code Assistance Required
Overly Personal etc ect end up as hundreds.
The Whole community can interact and comment if they choose but once an the admin comments the buck stops there. Agree or Disagree is irrelevant take the view that decision may change if is an 'opinion' matter. Every additional comment past this point will have to create a request to be added. With no restricted time duration.  Some of these will technically assist members directions on their paths. Then Create a transcript give it some key words and log it in the tutorial sections somewhere, as currently all the wonderful topics you beautiful people are discussing are being lost and people will be constantly reinventing the wheel and treading over old ground. Ever been asked the same Questions twice?   Be nice if in a thousand years the discussions embraced tomorrow could help direct people through the history of 'how' and why things work the way they do and how they evolved.  Admins discretion by all means delete the trivial!!! But if of importance leave it out there for everyone.  Important not to get key players to bogged down with this so maybe an 'Entrusted Group' should be set up of willing participants which grows with the projects.

**Comment by MattDorrian** [comment]
Mitzi's Mini CoC
Intrinsic Core Values I think you were seeking of a way to 'Simplify' the CoC to avoid Lengthy mediation processes. Core Foundation Words are as simple as it gets. Easy to remember and define where something is in breach.  It would naturally do some of the heavy lifting and consume less of peoples time. These are the ones I use there may well be others people can think of?  But they can often be defined better by one of the Words below.  Simpler the better.

GOOD - always over bad
RIGHT - instead of wrong
INTEGRITY - the moral compass
COMMON SENSE - its not that common
GREED - take only what you need and leave some for others
VISION - the direction is forwards yet sometimes backwards is the only way to get back on track
BEST - build it to achieve the best or someone will build it better
SUSTAINABLE - create and build like you mean it to be there in there end
HOPE - allowed to dream
HELP - the best feeling in the world when given or received. - Wherever we can
VOICE - on its own is divided and quiet yet when United can become too loud to ignore
ACCEPT - to be tolerant of others and Change   
TRUST - ( I have a plan for this)
FREEDOM - the right to live as free as every other living creature on our planet and beyond
PROTECT - the responsibility for everything alive now and the future to a have a chance to exist
SAFE - everything has the right to feel safe
PROBLEMS - have never existed only issues that require a solution everything can be solved
LOVE - the Ultimate gift to give and receive, where our fondest memories reside, love only grows stronger when given completely - It is our strongest emotion give it all to whoever you choose, it never runs out.  

The top 2 cover 90% of issues the other 10% covers Personal Opinion and the bottom one stands alone. Much like Free Will and Thought which must be promised to never be even encroached on.
I have something else that will help but going to have to dig it out.  Hope some of this may be of some help. I can probably change the format so its easy to read in a script format. maybe we should hold fire just a bit until all are ready and ease it in where necessary.

**Comment by Mitzi-Laszlo** [comment]
Just to clarify on scope. The code of conduct is for [Solid](https://github.com/solid) which is supported by the [Solid Team](https://github.com/solid/community/blob/master/community-roles.md)

@mediaprophet Thank you for sharing https://www.w3.org/Consortium/pwe/ and https://www.w3.org/Consortium/cepc/ suggestion

**Comment by MattDorrian** [comment]
Suspect it goes much higher and further than that. In that case may only
need a little guidance later on. All the Best


<http://www.avg.com/email-signature?utm_medium=email&utm_source=link&utm_campaign=sig-email&utm_content=webmail>
Virus-free.
www.avg.com
<http://www.avg.com/email-signature?utm_medium=email&utm_source=link&utm_campaign=sig-email&utm_content=webmail>
<#DAB4FAD8-2DD7-40BB-A1B8-4E2AA1F9FDF2>

**Comment by mediaprophet** [comment]
Timbl says it better than could otherwise be expected.

https://www.wired.com/story/tim-berners-lee-world-wide-web-anniversary/

https://webfoundation.org/2019/03/web-birthday-30/

Imho,

it's our job to back him (& each other) up.

So, we've got a lot of work to do to ensure the values he illustrates to be
important, are able to be consumed and made useful via rdf.

**Comment by Mitzi-Laszlo** [comment]
http://www3.weforum.org/docs/Code_of_Conduct_2017.pdf perhaps a model to refer to?

**Comment by megoth** [comment]
@Mitzi-Laszlo that is an impressive document, very detailed and well structured! I especially like one of the last pages called "Talk to us" that describes the process of reporting an incident.

I like it very much, although it's a bit big (20 pages). That being said, I think it's a good model that we can learn a lot from 😸

**Comment by Mitzi-Laszlo** [comment]
Yes, ok - looks like we still would like to keep a code of conduct so I'll close this pull request.

**Comment by MattDorrian** [comment]
That's the spirit Mitzi.
Arne Sometimes some things have to be stretched to be fully understood!
I Hope to one day to see both of your faces smiling.  If you ever get stuck
Sustainable is the word to follow.
I wish you both all the Love in the world.

Peace

**Comment by mediaprophet** [comment]
I don't understand why it was ever considered that one wasn't needed.

Are you able to enlighten us?

Can you also clarify how it is applied to 3rd party documents?

If you want to share a document from your google drive, I can graffiti all
over it, and we could explore the considerations that way, if it's helpful.

Certainly worked for others with one of my documents.

Good to see it didn't result in no code of conduct for inrupt, whilst
noting, anything like.rule.of law is only useful if enforced.

If a law is not enforced, it doesn't really matter.

Looking forward to getting that link to your creative work, noting, please
ensure the comments function is turned on, as I think the code of conduct
is fairly clear about what I can do with it, and what your means for
recourse is no matter how I do so.

After all, if something is said.about it, it'll only make the situation
worse for them.

Perhaps this can go into the tactical ethics section...

**Pull request closed without merging**
