### PR TITLE
Create issue-template.md

### PR DESCRIPTION
**Pull request by Mitzi-Laszlo**

### CODE REVIEW

**Comment by justinwb** [comment]
Github allows us to create real templates that can be used for issues and pull requests. I propose that we take the items here and make a template for each:

https://help.github.com/articles/creating-issue-templates-for-your-repository/

**Comment by Mitzi-Laszlo** [comment]
@justinwb excellent idea. The settings are not appearing like in the instructions for me. Could it be that there are admin settngs?

**Comment by Mitzi-Laszlo** [comment]
settings, also.

**Comment by Mitzi-Laszlo** [comment]
Sorted https://github.com/solid/community/tree/master/.github/ISSUE_TEMPLATE

**Pull request closed without merging**
